# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=20, unique=True)),
                ('lastName', models.TextField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
            ],
        ),
    ]
